# Generated by Django 4.2.1 on 2023-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='teams',
            name='role',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
