# Generated by Django 4.2.1 on 2023-07-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
