# Generated by Django 4.2.1 on 2023-07-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spice_rating',
            new_name='spicerating',
        ),
    ]
