# Generated by Django 4.2.1 on 2023-07-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_spice_rating_product_spicerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spicerating',
            new_name='spice_rating',
        ),
    ]
