# Generated by Django 4.2.1 on 2023-07-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_spicerating_product_spice_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spice_rating',
            new_name='spicerating',
        ),
    ]
